# Generated by Django 5.1.6 on 2025-04-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profileupdate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='posts_img/'),
        ),
    ]
